services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins/
      dockerfile: ./Dockerfile
    ports:
      - 50000:50000 # Jenkins agent port
    environment:
      - "PROMETHEUS_ENDPOINT=/jenkins_metrics/"
  nginx:
    container_name: nginx
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.49.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  prometheus_data: {}
