services:
  jenkins:
    build:
      context: ./jenkins/
      dockerfile: ./jenkins/Dockerfile
    # ports:
    #   - 8080:8080
    #   - 50000:50000
  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins
